### ISSUE TITLE
Can you add the ability to sort text fields in addiciton to numeric fields?

### ISSUE THREAD

**Issue by joeledvina** [pedrocamargo/getthemfiltered#6]
It seems like the values from numeric fields are automatically sorted numerically-ascending. Can text fields be sorted alphabetically? I can't tell how the order for a text field is determined, and it seems fairly haphazard. This makes the tool basically unusable for a text field with hundreds of values. The ability to search the values would also suffice. Having both options would be perfect!

This does look like a great alternative to the built-in Filter Query Builder (which I'm surprised you did not show in your YouTube video -- you access it by choosing "Filter..." in the right-click menu). That tool has a major annoyance for me: you either have to clear the filter before filtering again, or you have to use the "Test" button, but then you can't interact with the map whle the filter window is open. On the other hand, the Values pane in that tool does sort alphabetically and also includes a very fast search box.

**Comment by pedrocamargo** [comment]
Good catch/idea. 
It is done and the new version has been uploaded to the repository (it usually takes from 12 to 48h for it to be approved).
Searching makes it a little more complicated and would take me some time to implement (time that I don't have right now).  You are welcome to open a new issue with that feature request alone and I will get to it someday.

**Comment by pedrocamargo** [comment]
The plugin is now approved.

**Comment by joeledvina** [comment]
This is great. I had been thinking my workaround was at least as fast (keeping the Layer Styling pane docked on the right with the layer categorized by the field I'm interested in), but now that I'm doing this task again, I'm loving this tool. Thank you!

**Comment by pedrocamargo** [comment]
The auto-filtering while typing is a great idea too.  Can you add that as another issue?  I will label as enhancement and hopefully do it whenever I have some time
