### ISSUE TITLE
Filter the "filterable" layers

### ISSUE THREAD

**Issue by Swederman** [pedrocamargo/getthemfiltered#9]
Hi Pedro, 

Thanks for this plugin. I find it extremely powerful to go through many possible filters in one click. 

Where should I look in the code in order to filter the list of filterable layers (the first box) based on either :
- layer name (for instance only display layers that starts with a certain string sequence
- layer group/sub group 

Thanks in advance,

**Comment by pedrocamargo** [comment]
@Swederman , I  am not exactly sure what you are trying to do here.  If what you want to do is to be able to go to select a layer faster, then you will need to look into the QgsMapLayerComboBox, which is a custom QGIS object.  I would also recommend opening the ui_filter.ui file in QtDesigner (you may have installed it when you installed QGIS).

**Comment by Swederman** [comment]
Thanks a lot for your feedback, I'll look into that
